version: '3.8'

services:

  stock-portfolio:
    container_name: stock-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8888:3000
    environment:
      - CHOKIDAR_USEPOLLING=true